### ISSUE TITLE
One small problem

### ISSUE THREAD

**Issue by clauber115** [KevinStern/software-and-algorithms#7]
Hey Kevin! I've got an issue that's come up. I'm using this data set:

17.713713000	57.958889000	39.219360889	43.199387000
10.286681000	33.691383000	22.793575000	25.107962000
6.452791200	21.143085000	14.302735000	15.755548000
6.823037600	22.344730000	15.117439000	16.652315000
4.389327500	14.373154000	9.724390000	10.711688000

and when I run it through this website (link below) it comes up with a JUST slightly different answer. I'm not sure if it's an issue with my transcribing your implementation into fortran and I was wondering if you'd help me trouble shoot it. The error comes up with the third and fourth column. The websites solves row 4 as the best for the third column and row 3 for the fourth column. However your implementation does the reverse. All the other columns are correct. Any ideas on what might be causing this disparity? I've scoured the code and can't seem to find anything.
http://hungarianalgorithm.com/solve.php?c=17.713713-57.958889-39.219360889-43.199387--10.286681-33.691383-22.793575-25.107962--6.4527912-21.143085-14.302735-15.755548--6.8230376-22.344730-15.117439-16.652315--4.3893275-14.373154-9.7243900-10.711688

Much appreciated!

**Comment by KevinStern** [comment]
The following test passes:

    double[][] matrix = new double[][] {
        new double[] {17.713713000, 57.958889000, 39.219360889,
43.199387000},
        new double[] {10.286681000, 33.691383000, 22.793575000,
25.107962000},
        new double[] {6.452791200, 21.143085000, 14.302735000,
15.755548000},
        new double[] {6.823037600, 22.344730000, 15.117439000,
16.652315000},
        new double[] {4.389327500, 14.373154000, 9.724390000,
10.711688000}};
    HungarianAlgorithm b = new HungarianAlgorithm(matrix);
    int[] match = b.execute();
    Assert.assertTrue(Arrays.equals(new int[] { -1, 0, 3, 2, 1 }, match));
    Assert.assertEquals(55.532821999, computeCost(matrix, match),
0.0000001);

This jibes with the website to which you linked.

**Comment by clauber115** [comment]
Okay, then it must be my transcription that is messing it up. Thanks for testing it for me!
