### ISSUE TITLE
Compile and Use with examples

### ISSUE THREAD

**Issue by maki-markie** [KevinStern/software-and-algorithms#8]
Hi there Kevin!

Can you please tell me how to compile the Hungarian Algorithm and use with examples? Thanks a lot!

Regards,
Maki

**Comment by KevinStern** [comment]
The project structure adheres to maven conventions; have a look at the "Getting Started" guide for information on how to compile a maven project:  https://maven.apache.org/guides/getting-started/index.html.

Note also that the project is available through the maven central repository, in case you don't want to compile the code yourself:  https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22software-and-algorithms%22.
